using Microsoft.VisualStudio.TestTools.UnitTesting;

// The following code was generated by Microsoft Test Code
//  Generation V1.0. The test owner should check each test
//  for validity.

namespace Sharp3D.Math.Core.Tests
{
	/// <summary>
	/// This is a test class for Matrix3F and is intended
	/// to contain all Matrix3F Unit Tests
	/// </summary>
	[TestClass()]
	public class Matrix3FTest
	{
		#region Initialization\Cleanup
		/// <summary>
		/// Initialize() is called once during test execution before
		/// test methods in this test class are executed.
		/// </summary>
		[TestInitialize()]
		public void Initialize()
		{
			//  TODO: Add test initialization code
		}

		/// <summary>
		/// Cleanup() is called once during test execution after
		/// test methods in this class have executed unless
		/// this test class' Initialize() method throws an exception.
		/// </summary>
		[TestCleanup()]
		public void Cleanup()
		{
			//  TODO: Add test cleanup code
		}
		#endregion

		#region TestContext
		private TestContext m_testContext = null;

		public TestContext TestContext
		{
			get { return m_testContext; }
			set { m_testContext = value; }
		}
		#endregion

		#region Constructors Tests
		/// <summary>
		/// ConstructorTest is a test case for Matrix3F (float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float)
		/// </summary>
		[TestMethod()]
		public void ConstructorTest()
		{
			float m11 = 1;
			float m12 = 2;
			float m13 = 3;
			float m21 = 4;
			float m22 = 5;
			float m23 = 6;
			float m31 = 7;
			float m32 = 8;
			float m33 = 9;

			Sharp3D.Math.Core.Matrix3F target = new Sharp3D.Math.Core.Matrix3F(m11, m12, m13, m21, m22, m23, m31, m32, m33);

			Assert.AreEqual(m11, target.M11);
			Assert.AreEqual(m12, target.M12);
			Assert.AreEqual(m13, target.M13);
			Assert.AreEqual(m21, target.M21);
			Assert.AreEqual(m22, target.M22);
			Assert.AreEqual(m23, target.M23);
			Assert.AreEqual(m31, target.M31);
			Assert.AreEqual(m32, target.M32);
			Assert.AreEqual(m33, target.M33);
		}

		/// <summary>
		/// ConstructorTest1 is a test case for Matrix3F (float[])
		/// </summary>
		[TestMethod()]
		public void ConstructorTest1()
		{
			float[] elements = new float[9] { 1, 2, 3, 4, 5, 6, 7, 8, 9 };

			Sharp3D.Math.Core.Matrix3F target = new Sharp3D.Math.Core.Matrix3F(elements);

			Assert.AreEqual(elements[0], target.M11);
			Assert.AreEqual(elements[1], target.M12);
			Assert.AreEqual(elements[2], target.M13);
		
			Assert.AreEqual(elements[3], target.M21);
			Assert.AreEqual(elements[4], target.M22);
			Assert.AreEqual(elements[5], target.M23);
			
			Assert.AreEqual(elements[6], target.M31);
			Assert.AreEqual(elements[7], target.M32);
			Assert.AreEqual(elements[8], target.M33);
		}

		/// <summary>
		/// ConstructorTest2 is a test case for Matrix3F (Sharp3D.Math.Core.Matrix3F)
		/// </summary>
		[TestMethod()]
		public void ConstructorTest2()
		{
			Sharp3D.Math.Core.Matrix3F m = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			Sharp3D.Math.Core.Matrix3F target = new Sharp3D.Math.Core.Matrix3F(m);

			Assert.AreEqual(m.M11, target.M11);
			Assert.AreEqual(m.M12, target.M12);
			Assert.AreEqual(m.M13, target.M13);
			Assert.AreEqual(m.M21, target.M21);
			Assert.AreEqual(m.M22, target.M22);
			Assert.AreEqual(m.M23, target.M23);
			Assert.AreEqual(m.M31, target.M31);
			Assert.AreEqual(m.M32, target.M32);
			Assert.AreEqual(m.M33, target.M33);
		}

		/// <summary>
		/// ConstructorTest3 is a test case for Matrix3F (Sharp3D.Math.Core.Vector3F, Sharp3D.Math.Core.Vector3F, Sharp3D.Math.Core.Vector3F, Sharp3D.Math.Core.Vector3F)
		/// </summary>
		[TestMethod()]
		public void ConstructorTest3()
		{
			Sharp3D.Math.Core.Vector3F column1 = new Sharp3D.Math.Core.Vector3F(1, 4, 7);
			Sharp3D.Math.Core.Vector3F column2 = new Sharp3D.Math.Core.Vector3F(2, 5, 8);
			Sharp3D.Math.Core.Vector3F column3 = new Sharp3D.Math.Core.Vector3F(3, 6, 9);

			Sharp3D.Math.Core.Matrix3F target = new Sharp3D.Math.Core.Matrix3F(column1, column2, column3);

			Assert.AreEqual(1.0f, target.M11);
			Assert.AreEqual(2.0f, target.M12);
			Assert.AreEqual(3.0f, target.M13);
			Assert.AreEqual(4.0f, target.M21);
			Assert.AreEqual(5.0f, target.M22);
			Assert.AreEqual(6.0f, target.M23);
			Assert.AreEqual(7.0f, target.M31);
			Assert.AreEqual(8.0f, target.M32);
			Assert.AreEqual(9.0f, target.M33);
		}
		#endregion

		#region Public Properties Tests
		/// <summary>
		/// GetTraceTest is a test case for Trace property
		/// </summary>
		[TestMethod()]
		public void TraceTest()
		{
			Sharp3D.Math.Core.Matrix3F target = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);

			float expected = 1.0f + 5.0f + 9.0f;
			float actual = target.Trace;
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region ICloneable Tests
		/// <summary>
		/// CloneTest is a test case for Clone ()
		/// </summary>
		[TestMethod()]
		public void CloneTest()
		{
			Sharp3D.Math.Core.Matrix3F m = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			Sharp3D.Math.Core.Matrix3F target = new Sharp3D.Math.Core.Matrix3F(m);
			Sharp3D.Math.Core.Matrix3F expected = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);

			Sharp3D.Math.Core.Matrix3F actual = target.Clone();
			Assert.AreEqual(expected, actual);
		}

		#endregion

		#region Public Static Parse Methods Tests
		/// <summary>
		/// ParseTest is a test case for Parse (string)
		/// </summary>
		[TestMethod()]
		public void ParseTest()
		{
			string value;
			Sharp3D.Math.Core.Matrix3F expected = new Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			Sharp3D.Math.Core.Matrix3F actual;

			value = "3x3[1,2,3,4,5,6,7,8,9]";
			actual = Sharp3D.Math.Core.Matrix3F.Parse(value);
			Assert.AreEqual(expected, actual);

			value = "3x3  [1, 2,3,4, 5 ,6,7,8,9]";
			actual = Sharp3D.Math.Core.Matrix3F.Parse(value);
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// ParseTest is a test case for Parse (string)
		/// Verifies the exception thrown when illegal input is given.
		/// </summary>
		[TestMethod()]
		[ExpectedException(typeof(Sharp3D.Math.Core.ParseException))]
		public void ParseExceptionTest()
		{
			Sharp3D.Math.Core.Matrix3F.Parse("[1,2]");
		}
		/// <summary>
		/// TryParseTest is a test case for TryParse (string, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void TryParseTest()
		{
			string value = "3x3[1, 2, 3, 4, 5,6, 7, 8, 9]";
			Sharp3D.Math.Core.Matrix3F result = Matrix3F.Zero;

			Sharp3D.Math.Core.Matrix3F expectedResult = new Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			bool expected = true;
			bool actual;

			actual = Sharp3D.Math.Core.Matrix3F.TryParse(value, out result);
			Assert.AreEqual(expected, actual);
			Assert.AreEqual(expectedResult, result);
		}
		[TestMethod()]
		public void TryParseFailTest()
		{
			string value = "[1,2)";
			Sharp3D.Math.Core.Matrix3F result = Matrix3F.Zero;

			Matrix3F expectedResult = Matrix3F.Zero;
			bool expected = false;
			bool actual;

			actual = Sharp3D.Math.Core.Matrix3F.TryParse(value, out result);
			Assert.AreEqual(expected, actual);
			Assert.AreEqual(expectedResult, result);
		}
		#endregion

		#region Public Metods Tests
		/// <summary>
		/// GetDeterminantTest is a test case for GetDeterminant ()
		/// </summary>
		[TestMethod()]
		public void GetDeterminantTest()
		{
			Sharp3D.Math.Core.Matrix3F target;
			float expected;
			float actual;

			target = new Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			expected = 0.0f;
			actual = target.GetDeterminant();
			Assert.AreEqual(expected, actual);

			target = new Matrix3F(1, 0, 4, 3, 1, 6, 7, 8, 1);
			expected = 21.0f;
			actual = target.GetDeterminant();
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// TransposeTest is a test case for Transpose ()
		/// </summary>
		[TestMethod()]
		public void TransposeTest()
		{
			Sharp3D.Math.Core.Matrix3F source = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			Sharp3D.Math.Core.Matrix3F target = new Sharp3D.Math.Core.Matrix3F(source);
			Sharp3D.Math.Core.Matrix3F expected = new Matrix3F(1, 4, 7, 2, 5, 8, 3, 6, 9);

			target.Transpose();

			Assert.AreEqual(expected, target);
		}
		#endregion

		#region System.Object Overrides Tests
		/// <summary>
		/// EqualsTest is a test case for Equals (object)
		/// </summary>
		[TestMethod()]
		public void EqualsTest()
		{
			Sharp3D.Math.Core.Matrix3F m = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			Sharp3D.Math.Core.Matrix3F target = new Sharp3D.Math.Core.Matrix3F(m);

			bool expected;
			bool actual;

			expected = true;
			actual = target.Equals(m);
			Assert.AreEqual(expected, actual, m.ToString() + " should be equal to " + target.ToString());

			expected = false;
			m.M11 = 10;
			actual = target.Equals(m);
			Assert.AreEqual(expected, actual, m.ToString() + " should not be equal to " + target.ToString());
		}
		/// <summary>
		/// ToStringTest is a test case for ToString ()
		/// </summary>
		[TestMethod()]
		public void ToStringTest()
		{
			Sharp3D.Math.Core.Matrix3F target = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);

			string expected = "3x3[1, 2, 3, 4, 5, 6, 7, 8, 9]";
			string actual;

			actual = target.ToString();
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region Public Static Matrix Arithmetics
		/// <summary>
		/// AddMatrixScalarResultTest is a test case for Add (Sharp3D.Math.Core.Matrix3F, float, Sharp3D.Math.Core.Matrix3F)
		/// </summary>
		[TestMethod()]
		public void AddMatrixScalarResultTest()
		{
			Sharp3D.Math.Core.Matrix3F matrix = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			float scalar = 1.0f;
			Sharp3D.Math.Core.Matrix3F result = new Sharp3D.Math.Core.Matrix3F();
			Sharp3D.Math.Core.Matrix3F expected = new Matrix3F(2, 3, 4, 5, 6, 7, 8, 9, 10);

			Sharp3D.Math.Core.Matrix3F.Add(matrix, scalar, ref result);

			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// AddMatrixMatrixResultTest is a test case for Add (Sharp3D.Math.Core.Matrix3F, Sharp3D.Math.Core.Matrix3F, Sharp3D.Math.Core.Matrix3F)
		/// </summary>
		[TestMethod()]
		public void AddMatrixMatrixResultTest()
		{
			Sharp3D.Math.Core.Matrix3F left = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			Sharp3D.Math.Core.Matrix3F right = new Sharp3D.Math.Core.Matrix3F(9, 8, 7 ,6, 5, 4, 3, 2, 1);
			Sharp3D.Math.Core.Matrix3F result = Sharp3D.Math.Core.Matrix3F.Zero;
			Sharp3D.Math.Core.Matrix3F expected = new Sharp3D.Math.Core.Matrix3F(10, 10, 10, 10, 10, 10, 10, 10, 10);

			Sharp3D.Math.Core.Matrix3F.Add(left, right, ref result);

			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// SubtractMatrixScalarResultTest is a test case for Subtract (Sharp3D.Math.Core.Matrix3F, float, Sharp3D.Math.Core.Matrix3F)
		/// </summary>
		[TestMethod()]
		public void SubtractMatrixScalarResultTest()
		{
			Sharp3D.Math.Core.Matrix3F matrix = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			float scalar = 1.0f;
			Sharp3D.Math.Core.Matrix3F result = Sharp3D.Math.Core.Matrix3F.Zero;
			Sharp3D.Math.Core.Matrix3F expected = new Sharp3D.Math.Core.Matrix3F(0, 1, 2, 3, 4, 5, 6, 7, 8);

			Sharp3D.Math.Core.Matrix3F.Subtract(matrix, scalar, ref result);

			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// SubtractTest3 is a test case for Subtract (Sharp3D.Math.Core.Matrix3F, Sharp3D.Math.Core.Matrix3F, Sharp3D.Math.Core.Matrix3F)
		/// </summary>
		[TestMethod()]
		public void SubtractMatrixMatrixResultTest()
		{
			Sharp3D.Math.Core.Matrix3F left = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			Sharp3D.Math.Core.Matrix3F right = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			Sharp3D.Math.Core.Matrix3F result = Sharp3D.Math.Core.Matrix3F.Identity;
			Sharp3D.Math.Core.Matrix3F expected = Sharp3D.Math.Core.Matrix3F.Zero;

			Sharp3D.Math.Core.Matrix3F.Subtract(left, right, ref result);

			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// MultiplyMatrixMatrixResultTest is a test case for Multiply (Sharp3D.Math.Core.Matrix3F, Sharp3D.Math.Core.Matrix3F, Sharp3D.Math.Core.Matrix3F)
		/// </summary>
		[TestMethod()]
		public void MultiplyMatrixMatrixResultTest()
		{
			Sharp3D.Math.Core.Matrix3F left = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			Sharp3D.Math.Core.Matrix3F right = new Sharp3D.Math.Core.Matrix3F(1, 0, 4, 3, 1, 6, 7, 8, 1);
			Sharp3D.Math.Core.Matrix3F result = Sharp3D.Math.Core.Matrix3F.Zero;
			Sharp3D.Math.Core.Matrix3F expected = new Sharp3D.Math.Core.Matrix3F(28, 26, 19, 61, 53, 52, 94, 80, 85);

			Sharp3D.Math.Core.Matrix3F.Multiply(left, right, ref result);

			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// TransposeTest1 is a test case for Transpose (Sharp3D.Math.Core.Matrix3F)
		/// </summary>
		[TestMethod()]
		public void TransposeTest1()
		{
			Sharp3D.Math.Core.Matrix3F m = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			Sharp3D.Math.Core.Matrix3F expected = new Matrix3F(1, 4, 7, 2, 5, 8, 3, 6, 9);
			Sharp3D.Math.Core.Matrix3F actual;

			actual = Sharp3D.Math.Core.Matrix3F.Transpose(m);
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region Comparison Operators Tests
		/// <summary>
		/// ValueEqualityTest is a test case for operator ==
		/// </summary>
		[TestMethod()]
		public void ValueEqualityTest()
		{
			Sharp3D.Math.Core.Matrix3F left;
			Sharp3D.Math.Core.Matrix3F right;

			bool expected;
			bool actual;

			left = new Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			right = new Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			expected = true;
			actual = (left == right);
			Assert.AreEqual(expected, actual);

			left = new Matrix3F(1, 2, 3, 4, 5, 61, 7, 8, 9);
			right = new Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			expected = false;
			actual = (left == right);
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// NotEqualTest is a test case for operator !=
		/// </summary>
		[TestMethod()]
		public void NotEqualTest()
		{
			Sharp3D.Math.Core.Matrix3F left;
			Sharp3D.Math.Core.Matrix3F right;

			bool expected;
			bool actual;

			left = new Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			right = new Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			expected = false;
			actual = (left != right);
			Assert.AreEqual(expected, actual);

			left = new Matrix3F(1, 2, 3, 4, 5, 61, 7, 8, 9);
			right = new Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			expected = true;
			actual = (left != right);
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region Binary Operators Tests
		/// <summary>
		/// SubtractMatrixMatrixTest is a test case for operator -
		/// </summary>
		[TestMethod()]
		public void SubtractMatrixMatrixTest()
		{
			Sharp3D.Math.Core.Matrix3F left = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			Sharp3D.Math.Core.Matrix3F right = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);

			Sharp3D.Math.Core.Matrix3F expected = Matrix3F.Zero;
			Sharp3D.Math.Core.Matrix3F actual;

			actual = left - right;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// SubtractMatrixScalarTest is a test case for operator -
		/// </summary>
		[TestMethod()]
		public void SubtractMatrixScalarTest()
		{
			Sharp3D.Math.Core.Matrix3F matrix = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			float scalar = 1.0f;

			Sharp3D.Math.Core.Matrix3F expected = new Sharp3D.Math.Core.Matrix3F(0, 1, 2, 3, 4, 5, 6, 7, 8);
			Sharp3D.Math.Core.Matrix3F actual;

			actual = matrix - scalar;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// MultiplyMatrixMatrixTest is a test case for operator *
		/// </summary>
		[TestMethod()]
		public void MultiplyMatrixMatrixTest()
		{
			Sharp3D.Math.Core.Matrix3F left = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			Sharp3D.Math.Core.Matrix3F right = new Sharp3D.Math.Core.Matrix3F(1, 0, 4, 3, 1, 6, 7, 8, 1);

			Sharp3D.Math.Core.Matrix3F expected = new Sharp3D.Math.Core.Matrix3F(28, 26, 19, 61, 53, 52, 94, 80, 85);
			Sharp3D.Math.Core.Matrix3F actual;

			actual = left * right;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// AddMatrixMatrixTest is a test case for operator +
		/// </summary>
		[TestMethod()]
		public void AddMatrixMatrixTest()
		{
			Sharp3D.Math.Core.Matrix3F left = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			Sharp3D.Math.Core.Matrix3F right = new Sharp3D.Math.Core.Matrix3F(9, 8, 7 ,6, 5, 4, 3, 2, 1);

			Sharp3D.Math.Core.Matrix3F expected = new Sharp3D.Math.Core.Matrix3F(10, 10, 10, 10, 10, 10, 10, 10, 10);
			Sharp3D.Math.Core.Matrix3F actual;

			actual = left + right;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// AddScalarMatrixTest is a test case for operator +
		/// </summary>
		[TestMethod()]
		public void AddScalarMatrixTest()
		{
			float scalar = 1.0f;
			Sharp3D.Math.Core.Matrix3F matrix = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);

			Sharp3D.Math.Core.Matrix3F expected = new Sharp3D.Math.Core.Matrix3F(2, 3, 4, 5, 6, 7, 8, 9, 10);
			Sharp3D.Math.Core.Matrix3F actual;

			actual = scalar + matrix;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// AddMatrixScalarTest is a test case for operator +
		/// </summary>
		[TestMethod()]
		public void AddMatrixScalarTest()
		{
			float scalar = 1.0f;
			Sharp3D.Math.Core.Matrix3F matrix = new Sharp3D.Math.Core.Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);

			Sharp3D.Math.Core.Matrix3F expected = new Sharp3D.Math.Core.Matrix3F(2, 3, 4, 5, 6, 7, 8, 9, 10);
			Sharp3D.Math.Core.Matrix3F actual;

			actual = matrix + scalar;
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region Index Operator Tests
		/// <summary>
		/// ItemTest is a test case for this[int index]
		/// </summary>
		[TestMethod()]
		public void ItemTest()
		{
			Sharp3D.Math.Core.Matrix3F target = new Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);

			Assert.AreEqual(target.M11, target[0]);
			Assert.AreEqual(target.M12, target[1]);
			Assert.AreEqual(target.M13, target[2]);

			Assert.AreEqual(target.M21, target[3]);
			Assert.AreEqual(target.M22, target[4]);
			Assert.AreEqual(target.M23, target[5]);

			Assert.AreEqual(target.M31, target[6]);
			Assert.AreEqual(target.M32, target[7]);
			Assert.AreEqual(target.M33, target[8]);
		}
		[TestMethod()]
		[ExpectedException(typeof(System.IndexOutOfRangeException))]
		public void ItemTest1()
		{
			Sharp3D.Math.Core.Matrix3F target = new Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);
			target[16]++;
		}
		/// <summary>
		/// ItemTest is a test case for this[int row, int column]
		/// </summary>
		[TestMethod()]
		public void ItemTest2()
		{
			Sharp3D.Math.Core.Matrix3F target = new Matrix3F(1, 2, 3, 4, 5, 6, 7, 8, 9);

			Assert.AreEqual(target.M11, target[1,1]);
			Assert.AreEqual(target.M12, target[1,2]);
			Assert.AreEqual(target.M13, target[1,3]);

			Assert.AreEqual(target.M21, target[2,1]);
			Assert.AreEqual(target.M22, target[2,2]);
			Assert.AreEqual(target.M23, target[2,3]);

			Assert.AreEqual(target.M31, target[3,1]);
			Assert.AreEqual(target.M32, target[3,2]);
			Assert.AreEqual(target.M33, target[3,3]);
		}
		#endregion

		/// <summary>
		/// TransformTest is a test case for Transform (Sharp3D.Math.Core.Matrix3F, Sharp3D.Math.Core.Vector3F)
		/// </summary>
		[TestMethod()]
		public void TransformMatrixVectorTest()
		{
			Sharp3D.Math.Core.Matrix3F matrix = new Sharp3D.Math.Core.Matrix3F(
				2,0,0,
				0,2,0,
				0,0,2
				);
			Sharp3D.Math.Core.Vector3F vector = new Sharp3D.Math.Core.Vector3F(1,2,3);

			Sharp3D.Math.Core.Vector3F expected = new Sharp3D.Math.Core.Vector3F(2,4,6);
			Sharp3D.Math.Core.Vector3F actual;

			actual = Sharp3D.Math.Core.Matrix3F.Transform(matrix, vector);
			Assert.AreEqual(expected, actual);
		}

		/// <summary>
		/// TransformMatrixVectorResultTest is a test case for Transform (Sharp3D.Math.Core.Matrix3F, Sharp3D.Math.Core.Vector3F, Sharp3D.Math.Core.Vector3F)
		/// </summary>
		[TestMethod()]
		public void TransformMatrixVectorResultTest()
		{
			Sharp3D.Math.Core.Matrix3F matrix = new Sharp3D.Math.Core.Matrix3F(
				2, 0, 0,
				0, 2, 0,
				0, 0, 2
				);
			Sharp3D.Math.Core.Vector3F vector = new Sharp3D.Math.Core.Vector3F(1, 2, 3);
			Sharp3D.Math.Core.Vector3F result = new Sharp3D.Math.Core.Vector3F();
			Sharp3D.Math.Core.Vector3F expected = new Sharp3D.Math.Core.Vector3F(2, 4, 6);

			Sharp3D.Math.Core.Matrix3F.Transform(matrix, vector, ref result);

			Assert.AreEqual(expected, result);
		}
	}
}
