using Microsoft.VisualStudio.TestTools.UnitTesting;

// The following code was generated by Microsoft Test Code
//  Generation V1.0. The test owner should check each test
//  for validity.

namespace Sharp3D.Math.Core.Tests
{
	/// <summary>
	/// This is a test class for Matrix2D and is intended
	/// to contain all Matrix2D Unit Tests
	/// </summary>
	[TestClass()]
	public class Matrix2DTest
	{
		#region Initialization\Cleanup
		/// <summary>
		/// Initialize() is called once during test execution before
		/// test methods in this test class are executed.
		/// </summary>
		[TestInitialize()]
		public void Initialize()
		{
			//  TODO: Add test initialization code
		}

		/// <summary>
		/// Cleanup() is called once during test execution after
		/// test methods in this class have executed unless
		/// this test class' Initialize() method throws an exception.
		/// </summary>
		[TestCleanup()]
		public void Cleanup()
		{
			//  TODO: Add test cleanup code
		}
		#endregion

		#region TestContext
		private TestContext m_testContext = null;

		public TestContext TestContext
		{
			get { return m_testContext; }
			set { m_testContext = value; }
		}
		#endregion

		#region Constructors Tests
		/// <summary>
		/// ConstructorTest is a test case for Matrix2D (double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double)
		/// </summary>
		[TestMethod()]
		public void ConstructorTest()
		{
			double m11 = 1;
			double m12 = 2;
			double m21 = 3;
			double m22 = 4;

			Sharp3D.Math.Core.Matrix2D target = new Sharp3D.Math.Core.Matrix2D(m11, m12, m21, m22);

			Assert.AreEqual(m11, target.M11);
			Assert.AreEqual(m12, target.M12);
			Assert.AreEqual(m21, target.M21);
			Assert.AreEqual(m22, target.M22);
		}

		/// <summary>
		/// ConstructorTest1 is a test case for Matrix2D (double[])
		/// </summary>
		[TestMethod()]
		public void ConstructorTest1()
		{
			double[] elements = new double[4] { 1, 2, 3, 4 };

			Sharp3D.Math.Core.Matrix2D target = new Sharp3D.Math.Core.Matrix2D(elements);

			Assert.AreEqual(elements[0], target.M11);
			Assert.AreEqual(elements[1], target.M12);
		
			Assert.AreEqual(elements[2], target.M21);
			Assert.AreEqual(elements[3], target.M22);
		}

		/// <summary>
		/// ConstructorTest2 is a test case for Matrix2D (Sharp3D.Math.Core.Matrix2D)
		/// </summary>
		[TestMethod()]
		public void ConstructorTest2()
		{
			Sharp3D.Math.Core.Matrix2D m = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			Sharp3D.Math.Core.Matrix2D target = new Sharp3D.Math.Core.Matrix2D(m);

			Assert.AreEqual(m.M11, target.M11);
			Assert.AreEqual(m.M12, target.M12);
			Assert.AreEqual(m.M21, target.M21);
			Assert.AreEqual(m.M22, target.M22);
		}

		/// <summary>
		/// ConstructorTest3 is a test case for Matrix2D (Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void ConstructorTest3()
		{
			Sharp3D.Math.Core.Vector2D column1 = new Sharp3D.Math.Core.Vector2D(1, 3);
			Sharp3D.Math.Core.Vector2D column2 = new Sharp3D.Math.Core.Vector2D(2, 4);

			Sharp3D.Math.Core.Matrix2D target = new Sharp3D.Math.Core.Matrix2D(column1, column2);

			Assert.AreEqual(1.0, target.M11);
			Assert.AreEqual(2.0, target.M12);
			Assert.AreEqual(3.0, target.M21);
			Assert.AreEqual(4.0, target.M22);
		}
		#endregion

		#region Public Properties Tests
		/// <summary>
		/// GetTraceTest is a test case for Trace property
		/// </summary>
		[TestMethod()]
		public void TraceTest()
		{
			Sharp3D.Math.Core.Matrix2D target = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);

			double expected = 1.0 + 4.0;
			double actual = target.Trace;
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region ICloneable Tests
		/// <summary>
		/// CloneTest is a test case for Clone ()
		/// </summary>
		[TestMethod()]
		public void CloneTest()
		{
			Sharp3D.Math.Core.Matrix2D m = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			Sharp3D.Math.Core.Matrix2D target = new Sharp3D.Math.Core.Matrix2D(m);
			Sharp3D.Math.Core.Matrix2D expected = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);

			Sharp3D.Math.Core.Matrix2D actual = target.Clone();
			Assert.AreEqual(expected, actual);
		}

		#endregion

		#region Public Static Parse Methods Tests
		/// <summary>
		/// ParseTest is a test case for Parse (string)
		/// </summary>
		[TestMethod()]
		public void ParseTest()
		{
			string value;
			Sharp3D.Math.Core.Matrix2D expected = new Matrix2D(1, 2, 3, 4);
			Sharp3D.Math.Core.Matrix2D actual;

			value = "2x2[1,2,3,4]";
			actual = Sharp3D.Math.Core.Matrix2D.Parse(value);
			Assert.AreEqual(expected, actual);

			value = "2x2  [1, 2,3,4]";
			actual = Sharp3D.Math.Core.Matrix2D.Parse(value);
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// ParseTest is a test case for Parse (string)
		/// Verifies the exception thrown when illegal input is given.
		/// </summary>
		[TestMethod()]
		[ExpectedException(typeof(Sharp3D.Math.Core.ParseException))]
		public void ParseExceptionTest()
		{
			Sharp3D.Math.Core.Matrix2D.Parse("[1,2]");
		}
		/// <summary>
		/// TryParseTest is a test case for TryParse (string, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void TryParseTest()
		{
			string value = "2x2[1, 2, 3, 4]";
			Sharp3D.Math.Core.Matrix2D result = Matrix2D.Zero;

			Sharp3D.Math.Core.Matrix2D expectedResult = new Matrix2D(1, 2, 3, 4);
			bool expected = true;
			bool actual;

			actual = Sharp3D.Math.Core.Matrix2D.TryParse(value, out result);
			Assert.AreEqual(expected, actual);
			Assert.AreEqual(expectedResult, result);
		}
		[TestMethod()]
		public void TryParseFailTest()
		{
			string value = "[1,2)";
			Sharp3D.Math.Core.Matrix2D result = Matrix2D.Zero;

			Matrix2D expectedResult = Matrix2D.Zero;
			bool expected = false;
			bool actual;

			actual = Sharp3D.Math.Core.Matrix2D.TryParse(value, out result);
			Assert.AreEqual(expected, actual);
			Assert.AreEqual(expectedResult, result);
		}
		#endregion

		#region Public Metods Tests
		/// <summary>
		/// GetDeterminantTest is a test case for GetDeterminant ()
		/// </summary>
		[TestMethod()]
		public void GetDeterminantTest()
		{
			Sharp3D.Math.Core.Matrix2D target;
			double expected;
			double actual;

			target = new Matrix2D(1, 2, 3, 4);
			expected = -2.0;
			actual = target.GetDeterminant();
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// TransposeTest is a test case for Transpose ()
		/// </summary>
		[TestMethod()]
		public void TransposeTest()
		{
			Sharp3D.Math.Core.Matrix2D source = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			Sharp3D.Math.Core.Matrix2D target = new Sharp3D.Math.Core.Matrix2D(source);
			Sharp3D.Math.Core.Matrix2D expected = new Matrix2D(1, 3, 2, 4);

			target.Transpose();

			Assert.AreEqual(expected, target);
		}
		#endregion

		#region System.Object Overrides Tests
		/// <summary>
		/// EqualsTest is a test case for Equals (object)
		/// </summary>
		[TestMethod()]
		public void EqualsTest()
		{
			Sharp3D.Math.Core.Matrix2D m = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			Sharp3D.Math.Core.Matrix2D target = new Sharp3D.Math.Core.Matrix2D(m);

			bool expected;
			bool actual;

			expected = true;
			actual = target.Equals(m);
			Assert.AreEqual(expected, actual, m.ToString() + " should be equal to " + target.ToString());

			expected = false;
			m.M11 = 10;
			actual = target.Equals(m);
			Assert.AreEqual(expected, actual, m.ToString() + " should not be equal to " + target.ToString());
		}
		/// <summary>
		/// ToStringTest is a test case for ToString ()
		/// </summary>
		[TestMethod()]
		public void ToStringTest()
		{
			Sharp3D.Math.Core.Matrix2D target = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);

			string expected = "2x2[1, 2, 3, 4]";
			string actual;

			actual = target.ToString();
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region Public Static Matrix Arithmetics
		/// <summary>
		/// AddMatrixScalarResultTest is a test case for Add (Sharp3D.Math.Core.Matrix2D, double, Sharp3D.Math.Core.Matrix2D)
		/// </summary>
		[TestMethod()]
		public void AddMatrixScalarResultTest()
		{
			Sharp3D.Math.Core.Matrix2D matrix = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			double scalar = 1.0;
			Sharp3D.Math.Core.Matrix2D result = new Sharp3D.Math.Core.Matrix2D();
			Sharp3D.Math.Core.Matrix2D expected = new Matrix2D(2, 3, 4, 5);

			Sharp3D.Math.Core.Matrix2D.Add(matrix, scalar, ref result);

			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// AddMatrixMatrixResultTest is a test case for Add (Sharp3D.Math.Core.Matrix2D, Sharp3D.Math.Core.Matrix2D, Sharp3D.Math.Core.Matrix2D)
		/// </summary>
		[TestMethod()]
		public void AddMatrixMatrixResultTest()
		{
			Sharp3D.Math.Core.Matrix2D left = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			Sharp3D.Math.Core.Matrix2D right = new Sharp3D.Math.Core.Matrix2D(4, 3, 2, 1);
			Sharp3D.Math.Core.Matrix2D result = Sharp3D.Math.Core.Matrix2D.Zero;
			Sharp3D.Math.Core.Matrix2D expected = new Sharp3D.Math.Core.Matrix2D(5, 5, 5, 5);

			Sharp3D.Math.Core.Matrix2D.Add(left, right, ref result);

			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// SubtractMatrixScalarResultTest is a test case for Subtract (Sharp3D.Math.Core.Matrix2D, double, Sharp3D.Math.Core.Matrix2D)
		/// </summary>
		[TestMethod()]
		public void SubtractMatrixScalarResultTest()
		{
			Sharp3D.Math.Core.Matrix2D matrix = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			double scalar = 1.0;
			Sharp3D.Math.Core.Matrix2D result = Sharp3D.Math.Core.Matrix2D.Zero;
			Sharp3D.Math.Core.Matrix2D expected = new Sharp3D.Math.Core.Matrix2D(0, 1, 2, 3);

			Sharp3D.Math.Core.Matrix2D.Subtract(matrix, scalar, ref result);

			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// SubtractTest3 is a test case for Subtract (Sharp3D.Math.Core.Matrix2D, Sharp3D.Math.Core.Matrix2D, Sharp3D.Math.Core.Matrix2D)
		/// </summary>
		[TestMethod()]
		public void SubtractMatrixMatrixResultTest()
		{
			Sharp3D.Math.Core.Matrix2D left = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			Sharp3D.Math.Core.Matrix2D right = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			Sharp3D.Math.Core.Matrix2D result = Sharp3D.Math.Core.Matrix2D.Identity;
			Sharp3D.Math.Core.Matrix2D expected = Sharp3D.Math.Core.Matrix2D.Zero;

			Sharp3D.Math.Core.Matrix2D.Subtract(left, right, ref result);

			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// MultiplyMatrixMatrixResultTest is a test case for Multiply (Sharp3D.Math.Core.Matrix2D, Sharp3D.Math.Core.Matrix2D, Sharp3D.Math.Core.Matrix2D)
		/// </summary>
		[TestMethod()]
		public void MultiplyMatrixMatrixResultTest()
		{
			Sharp3D.Math.Core.Matrix2D left = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			Sharp3D.Math.Core.Matrix2D right = new Sharp3D.Math.Core.Matrix2D(5, 6, 7, 8);
			Sharp3D.Math.Core.Matrix2D result = Sharp3D.Math.Core.Matrix2D.Zero;
			Sharp3D.Math.Core.Matrix2D expected = new Sharp3D.Math.Core.Matrix2D(19, 22, 43, 50);

			Sharp3D.Math.Core.Matrix2D.Multiply(left, right, ref result);

			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// TransposeTest1 is a test case for Transpose (Sharp3D.Math.Core.Matrix2D)
		/// </summary>
		[TestMethod()]
		public void TransposeTest1()
		{
			Sharp3D.Math.Core.Matrix2D m = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			Sharp3D.Math.Core.Matrix2D expected = new Matrix2D(1, 3, 2, 4);
			Sharp3D.Math.Core.Matrix2D actual;

			actual = Sharp3D.Math.Core.Matrix2D.Transpose(m);
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region Comparison Operators Tests
		/// <summary>
		/// ValueEqualityTest is a test case for operator ==
		/// </summary>
		[TestMethod()]
		public void ValueEqualityTest()
		{
			Sharp3D.Math.Core.Matrix2D left;
			Sharp3D.Math.Core.Matrix2D right;

			bool expected;
			bool actual;

			left = new Matrix2D(1, 2, 3, 4);
			right = new Matrix2D(1, 2, 3, 4);
			expected = true;
			actual = (left == right);
			Assert.AreEqual(expected, actual);

			left = new Matrix2D(1, 21, 3, 4);
			right = new Matrix2D(1, 2, 3, 4);
			expected = false;
			actual = (left == right);
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// NotEqualTest is a test case for operator !=
		/// </summary>
		[TestMethod()]
		public void NotEqualTest()
		{
			Sharp3D.Math.Core.Matrix2D left;
			Sharp3D.Math.Core.Matrix2D right;

			bool expected;
			bool actual;

			left = new Matrix2D(1, 2, 3, 4);
			right = new Matrix2D(1, 2, 3, 4);
			expected = false;
			actual = (left != right);
			Assert.AreEqual(expected, actual);

			left = new Matrix2D(1, 2, 31, 4);
			right = new Matrix2D(1, 2, 3, 4);
			expected = true;
			actual = (left != right);
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region Binary Operators Tests
		/// <summary>
		/// SubtractMatrixMatrixTest is a test case for operator -
		/// </summary>
		[TestMethod()]
		public void SubtractMatrixMatrixTest()
		{
			Sharp3D.Math.Core.Matrix2D left = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			Sharp3D.Math.Core.Matrix2D right = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);

			Sharp3D.Math.Core.Matrix2D expected = Matrix2D.Zero;
			Sharp3D.Math.Core.Matrix2D actual;

			actual = left - right;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// SubtractMatrixScalarTest is a test case for operator -
		/// </summary>
		[TestMethod()]
		public void SubtractMatrixScalarTest()
		{
			Sharp3D.Math.Core.Matrix2D matrix = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			double scalar = 1.0;

			Sharp3D.Math.Core.Matrix2D expected = new Sharp3D.Math.Core.Matrix2D(0, 1, 2, 3);
			Sharp3D.Math.Core.Matrix2D actual;

			actual = matrix - scalar;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// MultiplyMatrixMatrixTest is a test case for operator *
		/// </summary>
		[TestMethod()]
		public void MultiplyMatrixMatrixTest()
		{
			Sharp3D.Math.Core.Matrix2D left = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			Sharp3D.Math.Core.Matrix2D right = new Sharp3D.Math.Core.Matrix2D(5, 6, 7, 8);

			Sharp3D.Math.Core.Matrix2D expected = new Sharp3D.Math.Core.Matrix2D(19, 22, 43, 50);
			Sharp3D.Math.Core.Matrix2D actual;

			actual = left * right;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// AddMatrixMatrixTest is a test case for operator +
		/// </summary>
		[TestMethod()]
		public void AddMatrixMatrixTest()
		{
			Sharp3D.Math.Core.Matrix2D left = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);
			Sharp3D.Math.Core.Matrix2D right = new Sharp3D.Math.Core.Matrix2D(4, 3, 2, 1);

			Sharp3D.Math.Core.Matrix2D expected = new Sharp3D.Math.Core.Matrix2D(5, 5, 5, 5);
			Sharp3D.Math.Core.Matrix2D actual;

			actual = left + right;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// AddScalarMatrixTest is a test case for operator +
		/// </summary>
		[TestMethod()]
		public void AddScalarMatrixTest()
		{
			double scalar = 1.0;
			Sharp3D.Math.Core.Matrix2D matrix = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);

			Sharp3D.Math.Core.Matrix2D expected = new Sharp3D.Math.Core.Matrix2D(2, 3, 4, 5);
			Sharp3D.Math.Core.Matrix2D actual;

			actual = scalar + matrix;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// AddMatrixScalarTest is a test case for operator +
		/// </summary>
		[TestMethod()]
		public void AddMatrixScalarTest()
		{
			double scalar = 1.0;
			Sharp3D.Math.Core.Matrix2D matrix = new Sharp3D.Math.Core.Matrix2D(1, 2, 3, 4);

			Sharp3D.Math.Core.Matrix2D expected = new Sharp3D.Math.Core.Matrix2D(2, 3, 4, 5);
			Sharp3D.Math.Core.Matrix2D actual;

			actual = matrix + scalar;
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region Index Operator Tests
		/// <summary>
		/// ItemTest is a test case for this[int index]
		/// </summary>
		[TestMethod()]
		public void ItemTest()
		{
			Sharp3D.Math.Core.Matrix2D target = new Matrix2D(1, 2, 3, 4);

			Assert.AreEqual(target.M11, target[0]);
			Assert.AreEqual(target.M12, target[1]);

			Assert.AreEqual(target.M21, target[2]);
			Assert.AreEqual(target.M22, target[3]);
		}
		[TestMethod()]
		[ExpectedException(typeof(System.IndexOutOfRangeException))]
		public void ItemTest1()
		{
			Sharp3D.Math.Core.Matrix2D target = new Matrix2D(1, 2, 3, 4);
			target[16]++;
		}
		/// <summary>
		/// ItemTest is a test case for this[int row, int column]
		/// </summary>
		[TestMethod()]
		public void ItemTest2()
		{
			Sharp3D.Math.Core.Matrix2D target = new Matrix2D(1, 2, 3, 4);

			Assert.AreEqual(target.M11, target[1,1]);
			Assert.AreEqual(target.M12, target[1,2]);

			Assert.AreEqual(target.M21, target[2,1]);
			Assert.AreEqual(target.M22, target[2,2]);
		}
		#endregion

		/// <summary>
		/// TransformTest is a test case for Transform (Sharp3D.Math.Core.Matrix2D, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void TransformMatrixVectorTest()
		{
			Sharp3D.Math.Core.Matrix2D matrix = new Sharp3D.Math.Core.Matrix2D(
				2,0,
				0,2
				);
			Sharp3D.Math.Core.Vector2D vector = new Sharp3D.Math.Core.Vector2D(1,2);

			Sharp3D.Math.Core.Vector2D expected = new Sharp3D.Math.Core.Vector2D(2,4);
			Sharp3D.Math.Core.Vector2D actual;

			actual = Sharp3D.Math.Core.Matrix2D.Transform(matrix, vector);
			Assert.AreEqual(expected, actual);
		}

		/// <summary>
		/// TransformMatrixVectorResultTest is a test case for Transform (Sharp3D.Math.Core.Matrix2D, Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void TransformMatrixVectorResultTest()
		{
			Sharp3D.Math.Core.Matrix2D matrix = new Sharp3D.Math.Core.Matrix2D(
				2, 0,
				0, 2
				);
			Sharp3D.Math.Core.Vector2D vector = new Sharp3D.Math.Core.Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D result = new Sharp3D.Math.Core.Vector2D();
			Sharp3D.Math.Core.Vector2D expected = new Sharp3D.Math.Core.Vector2D(2, 4);

			Sharp3D.Math.Core.Matrix2D.Transform(matrix, vector, ref result);

			Assert.AreEqual(expected, result);
		}
	}
}
