using Sharp3D.Math.Core;
using System.ComponentModel;
using Microsoft.VisualStudio.TestTools.UnitTesting;

// The following code was generated by Microsoft Test Code
//  Generation V1.0. The test owner should check each test
//  for validity.

namespace Sharp3D.Math.Core.Tests
{
	/// <summary>
	/// This is a test class for Vector2D and is intended
	/// to contain all Vector2D Unit Tests
	/// </summary>
	[TestClass]
	public class Vector2DTest
	{
		#region Initialization\Cleanup
		/// <summary>
		/// Initialize() is called once during test execution before
		/// test methods in this test class are executed.
		/// </summary>
		[TestInitialize()]
		public void Initialize()
		{
			//  TODO: Add test initialization code
		}

		/// <summary>
		/// Cleanup() is called once during test execution after
		/// test methods in this class have executed unless
		/// this test class' Initialize() method throws an exception.
		/// </summary>
		[TestCleanup()]
		public void Cleanup()
		{
			//  TODO: Add test cleanup code
		}
		#endregion

		private TestContext m_testContext = null;
		public TestContext TestContext
		{
			get { return m_testContext; }
			set { m_testContext = value; }
		}

		#region Constructors Tests
		/// <summary>
		/// ConstructorTest is a test case for Vector2D (double, double, double, double)
		/// </summary>
		[TestMethod()]
		public void ConstructorTest()
		{
			double x = 1;
			double y = 2;

			Sharp3D.Math.Core.Vector2D target = new Sharp3D.Math.Core.Vector2D(x, y);

			Assert.AreEqual(x, target.X);
			Assert.AreEqual(y, target.Y);
		}

		/// <summary>
		/// ConstructorTest1 is a test case for Vector2D (double[])
		/// </summary>
		[TestMethod()]
		public void ConstructorTest1()
		{
			double[] coordinates = new double[2] { 1, 2 };

			Sharp3D.Math.Core.Vector2D target = new Sharp3D.Math.Core.Vector2D(coordinates);

			Assert.AreEqual(coordinates[0], target.X);
			Assert.AreEqual(coordinates[1], target.Y);
		}

		/// <summary>
		/// ConstructorTest2 is a test case for Vector2D (Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void ConstructorTest2()
		{
			Sharp3D.Math.Core.Vector2D vector = new Sharp3D.Math.Core.Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D target = new Sharp3D.Math.Core.Vector2D(vector);

			Assert.AreEqual(vector.X, target.X);
			Assert.AreEqual(vector.Y, target.Y);
		}
		#endregion

		#region Public Properties Tests
		/// <summary>
		/// XTest is a test case for X
		/// </summary>
		[TestMethod()]
		public void XTest()
		{
			Sharp3D.Math.Core.Vector2D target = Sharp3D.Math.Core.Vector2D.Zero;

			double val = 3.14;
			target.X = val;

			Assert.AreEqual(val, target.X);
		}
		/// <summary>
		/// YTest is a test case for Y
		/// </summary>
		[TestMethod()]
		public void YTest()
		{
			Sharp3D.Math.Core.Vector2D target = Sharp3D.Math.Core.Vector2D.Zero;

			double val = 3.14;
			target.Y = val;

			Assert.AreEqual(val, target.Y);
		}
		#endregion

		#region ICloneable test
		/// <summary>
		/// CloneTest is a test case for Clone ()
		/// </summary>
		[TestMethod()]
		public void CloneTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D actual;

			actual = vector.Clone();
			Assert.AreEqual(vector.X, actual.X);
			Assert.AreEqual(vector.Y, actual.Y);
		}
		#endregion

		#region Public Static Parse Methods Tests
		/// <summary>
		/// ParseTest is a test case for Parse (string)
		/// </summary>
		[TestMethod()]
		public void ParseTest()
		{
			string value;
			Sharp3D.Math.Core.Vector2D expected = new Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D actual;

			value = "(1,2)";
			actual = Sharp3D.Math.Core.Vector2D.Parse(value);
			Assert.AreEqual(expected, actual);

			value = "( 1,  2   )";
			actual = Sharp3D.Math.Core.Vector2D.Parse(value);
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// ParseTest is a test case for Parse (string)
		/// Verifies the exception thrown when illegal input is given.
		/// </summary>
		[TestMethod()]
		[ExpectedException(typeof(Sharp3D.Math.Core.ParseException))]
		public void ParseExceptionTest()
		{
			Sharp3D.Math.Core.Vector2D.Parse("[1,2]");
		}
		/// <summary>
		/// TryParseTest is a test case for TryParse (string, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void TryParseTest()
		{
			string value = "(1,2)";
			Sharp3D.Math.Core.Vector2D result = Vector2D.Zero;

			Vector2D expectedResult = new Vector2D(1, 2);
			bool expected = true;
			bool actual;

			actual = Sharp3D.Math.Core.Vector2D.TryParse(value, out result);
			Assert.AreEqual(expected, actual);
			Assert.AreEqual(expectedResult, result);
		}
		[TestMethod()]
		public void TryParseFailTest()
		{
			string value = "[1,2)";
			Sharp3D.Math.Core.Vector2D result = Vector2D.Zero;

			Vector2D expectedResult = Vector2D.Zero;
			bool expected = false;
			bool actual;

			actual = Sharp3D.Math.Core.Vector2D.TryParse(value, out result);
			Assert.AreEqual(expected, actual);
			Assert.AreEqual(expectedResult, result);
		}
		#endregion

		#region Public Methods Tests
		/// <summary>
		/// GetLengthTest is a test case for GetLength ()
		/// </summary>
		[TestMethod()]
		public void GetLengthTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(1, 2);

			double expected = System.Math.Sqrt(5);
			double actual;

			actual = vector.GetLength();
			Assert.AreEqual(expected, actual);
		}

		/// <summary>
		/// GetLengthSquaredTest is a test case for GetLengthSquared ()
		/// </summary>
		[TestMethod()]
		public void GetLengthSquaredTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(1, 2);

			double expected = 5;
			double actual;

			actual = vector.GetLengthSquared();
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// NormalizeTest is a test case for Normalize ()
		/// </summary>
		[TestMethod()]
		public void NormalizeTest()
		{
			Sharp3D.Math.Core.Vector2D target = new Vector2D(10, 20);

			target.Normalize();

			bool expected = true;
			bool actual = MathFunctions.ApproxEquals(target.GetLength(), 1.0);

			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// NormalizeExceptionTest is a test case for Normalize() where the vector length is zero.
		/// </summary>
		[TestMethod()]
		[ExpectedException(typeof(System.DivideByZeroException))]
		public void NormalizeExceptionTest()
		{
			Vector2D vector = Vector2D.Zero;
			vector.Normalize();
		}
		/// <summary>
		/// ClampZeroTest is a test case for ClampZero ()
		/// </summary>
		[TestMethod()]
		public void ClampZeroTest()
		{
			double tolerance = MathFunctions.EpsilonD;
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(tolerance / 3, tolerance / 2);
			Sharp3D.Math.Core.Vector2D expected = new Vector2D(0.0, 0.0);

			vector.ClampZero();

			Assert.AreEqual(vector, expected);
		}

		/// <summary>
		/// ClampZeroTest1 is a test case for ClampZero (double)
		/// </summary>
		[TestMethod()]
		public void ClampZeroTest1()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(0.5, 0.9);
			Sharp3D.Math.Core.Vector2D expected = new Vector2D(0.0, 0.0);
			double tolerance = 1.0;

			vector.ClampZero(tolerance);

			Assert.AreEqual(vector, expected);
		}
		#endregion

		#region System.Object Overrides Tests
		/// <summary>
		/// EqualsTest is a test case for Equals (object)
		/// </summary>
		[TestMethod()]
		public void EqualsTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D target = new Sharp3D.Math.Core.Vector2D(vector);

			bool expected = true;
			bool actual;

			actual = target.Equals(vector);
			Assert.AreEqual(expected, actual, vector.ToString() + " should be equal to " + target.ToString());

			expected = false;
			vector.X = 10;
			actual = target.Equals(vector);
			Assert.AreEqual(expected, actual, vector.ToString() + " should not be equal to " + target.ToString());
		}
		/// <summary>
		/// ToStringTest is a test case for ToString ()
		/// </summary>
		[TestMethod()]
		public void ToStringTest()
		{
			Sharp3D.Math.Core.Vector2D target = new Vector2D(1, 2);

			string expected = "(1, 2)";
			string actual;

			actual = target.ToString();
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region Public Static Vector Arithmetics Tests
		/// <summary>
		/// AddVectorScalarResultTest is a test case for Add (Sharp3D.Math.Core.Vector2D, double, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void AddVectorScalarResultTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Sharp3D.Math.Core.Vector2D(1, 2);
			double scalar = 1;
			Sharp3D.Math.Core.Vector2D expected = new Sharp3D.Math.Core.Vector2D(2, 3);
			Sharp3D.Math.Core.Vector2D result = Vector2D.Zero;

			Sharp3D.Math.Core.Vector2D.Add(vector, scalar, ref result);

			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// AddVectorVectorResultTest is a test case for Add (Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void AddVectorVectorResultTest()
		{
			Sharp3D.Math.Core.Vector2D left = new Sharp3D.Math.Core.Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D right = new Sharp3D.Math.Core.Vector2D(4, 3);
			Sharp3D.Math.Core.Vector2D expected = new Sharp3D.Math.Core.Vector2D(5, 5);

			Sharp3D.Math.Core.Vector2D result = Vector2D.Zero;

			Sharp3D.Math.Core.Vector2D.Add(left, right, ref result);
			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// SubtractScalarVectorTest is a test case for Subtract (double, Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void SubtractScalarVectorTest()
		{
			double scalar = 10.0;
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(9, 8);
			Sharp3D.Math.Core.Vector2D expected = new Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D result = Vector2D.Zero;

			Sharp3D.Math.Core.Vector2D.Subtract(scalar, vector, ref result);
			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// SubtractVectorScalarTest is a test case for Subtract (Sharp3D.Math.Core.Vector2D, double, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void SubtractVectorScalarTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(1, 2);
			double scalar = 1.0;
			Sharp3D.Math.Core.Vector2D expected = new Vector2D(0, 1);
			Sharp3D.Math.Core.Vector2D result = Vector2D.Zero;

			Sharp3D.Math.Core.Vector2D.Subtract(vector, scalar, ref result);
			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// SubtractVectorVectorTest is a test case for Subtract (Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void SubtractVectorVectorTest()
		{
			Sharp3D.Math.Core.Vector2D left = new Vector2D(11, 12);
			Sharp3D.Math.Core.Vector2D right = new Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D expected = new Vector2D(10, 10);

			Sharp3D.Math.Core.Vector2D result = Vector2D.Zero;

			Sharp3D.Math.Core.Vector2D.Subtract(left, right, ref result);
			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// DivideScalarVectorResultTest is a test case for Divide (double, Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void DivideScalarVectorResultTest()
		{
			double scalar = 24.0;
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(2, 3);
			Sharp3D.Math.Core.Vector2D expected = new Vector2D(12, 8);

			Sharp3D.Math.Core.Vector2D result = Vector2D.Zero;

			Sharp3D.Math.Core.Vector2D.Divide(scalar, vector, ref result);
			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// DivideVectorScalarResultTest is a test case for Divide (Sharp3D.Math.Core.Vector2D, double, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void DivideVectorScalarResultTest()
		{
			double scalar = 2.0;
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(2, 4);
			Sharp3D.Math.Core.Vector2D expected = new Vector2D(1, 2);

			Sharp3D.Math.Core.Vector2D result = Vector2D.Zero;
			Sharp3D.Math.Core.Vector2D.Divide(vector, scalar, ref result);

			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// DivideVectorVectorTest is a test case for Divide (Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void DivideVectorVectorTest()
		{
			Sharp3D.Math.Core.Vector2D left = new Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D right = new Vector2D(2, 4);

			Sharp3D.Math.Core.Vector2D expected = new Vector2D(0.5, 0.5);
			Sharp3D.Math.Core.Vector2D actual;

			actual = Sharp3D.Math.Core.Vector2D.Divide(left, right);
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// DivideVectorVectorResultTest is a test case for Divide (Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void DivideVectorVectorResultTest()
		{
			Sharp3D.Math.Core.Vector2D left = new Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D right = new Vector2D(2, 4);
			Sharp3D.Math.Core.Vector2D expected = new Vector2D(0.5, 0.5);

			Sharp3D.Math.Core.Vector2D result = Vector2D.Zero;
			Sharp3D.Math.Core.Vector2D.Divide(left, right, ref result);
			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// MultiplyVectorScalarTest is a test case for Multiply (Sharp3D.Math.Core.Vector2D, double, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void MultiplyVectorScalarTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(1, 2);
			double scalar = 2;
			Sharp3D.Math.Core.Vector2D expected = new Vector2D(2, 4);

			Sharp3D.Math.Core.Vector2D result = Vector2D.Zero;
			Sharp3D.Math.Core.Vector2D.Multiply(vector, scalar, ref result);

			Assert.AreEqual(expected, result);
		}
		/// <summary>
		/// ApproxEqualTest is a test case for ApproxEqual (Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void ApproxEqualTest()
		{
			Sharp3D.Math.Core.Vector2D left = new Sharp3D.Math.Core.Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D right = left + MathFunctions.EpsilonD;

			bool expected = true;
			bool actual;

			actual = Sharp3D.Math.Core.Vector2D.ApproxEqual(left, right);
			Assert.AreEqual(expected, actual);

			right = right + MathFunctions.EpsilonD;
			expected = false;

			actual = Sharp3D.Math.Core.Vector2D.ApproxEqual(left, right);
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// ApproxEqualTest1 is a test case for ApproxEqual (Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D, double)
		/// </summary>
		[TestMethod()]
		public void ApproxEqualTest1()
		{
			Sharp3D.Math.Core.Vector2D left = new Sharp3D.Math.Core.Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D right = new Sharp3D.Math.Core.Vector2D(1.09, 2.09);
			double tolerance = 0.1;

			bool expected = true;
			bool actual;

			actual = Sharp3D.Math.Core.Vector2D.ApproxEqual(left, right, tolerance);
			Assert.AreEqual(expected, actual);

			right = new Sharp3D.Math.Core.Vector2D(1.2, 2.2);
			expected = false;

			actual = Sharp3D.Math.Core.Vector2D.ApproxEqual(left, right, tolerance);
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// DotProductTest is a test case for DotProduct (Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void DotProductTest()
		{
			Sharp3D.Math.Core.Vector2D left = new Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D right = new Vector2D(4, 3);

			double expected = 10;
			double actual;

			actual = Sharp3D.Math.Core.Vector2D.DotProduct(left, right);
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// KrossProductTest is a test case for KrossProduct (Sharp3D.Math.Core.Vector2D, Sharp3D.Math.Core.Vector2D)
		/// </summary>
		[TestMethod()]
		public void KrossProductTest()
		{
			Sharp3D.Math.Core.Vector2D left = new Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D right = new Vector2D(4, 3);

			double expected = -5;
			double actual;

			actual = Sharp3D.Math.Core.Vector2D.KrossProduct(left, right);
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region Unary Operators Tests
		/// <summary>
		/// NegativeTest is a test case for operator -
		/// </summary>
		[TestMethod()]
		public void NegativeTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(1, 2);

			Sharp3D.Math.Core.Vector2D expected = new Vector2D(-1, -2);
			Sharp3D.Math.Core.Vector2D actual;

			actual = -vector;
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region Binary Operators Tests
		/// <summary>
		/// AddTest4 is a test case for operator +
		/// </summary>
		[TestMethod()]
		public void AddOpVectorScalarTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(1, 2);
			double scalar = 1.0;

			Sharp3D.Math.Core.Vector2D expected = new Vector2D(2, 3);
			Sharp3D.Math.Core.Vector2D actual;

			actual = vector + scalar;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// AddTest5 is a test case for operator +
		/// </summary>
		[TestMethod()]
		public void AddOpVectorVectorTest()
		{
			Sharp3D.Math.Core.Vector2D left = new Sharp3D.Math.Core.Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D right = new Sharp3D.Math.Core.Vector2D(4, 3);

			Sharp3D.Math.Core.Vector2D expected = new Sharp3D.Math.Core.Vector2D(5, 5);
			Sharp3D.Math.Core.Vector2D actual;

			actual = left + right;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// AddTest6 is a test case for operator +
		/// </summary>
		[TestMethod()]
		public void AddOpScalarVectorTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(1, 2);
			double scalar = 1.0;

			Sharp3D.Math.Core.Vector2D expected = new Vector2D(2, 3);
			Sharp3D.Math.Core.Vector2D actual;

			actual = scalar + vector;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// SubtractTest is a test case for operator -
		/// </summary>
		[TestMethod()]
		public void SubtractOpVectorScalarTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(1, 2);
			double scalar = 1.0;

			Sharp3D.Math.Core.Vector2D expected = new Vector2D(0, 1);
			Sharp3D.Math.Core.Vector2D actual;

			actual = vector - scalar;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// SubtractTest1 is a test case for operator -
		/// </summary>
		[TestMethod()]
		public void SubtractOpScalarVectorTest()
		{
			double scalar = 10;
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(9, 8);

			Sharp3D.Math.Core.Vector2D expected = new Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D actual;

			actual = scalar - vector;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// SubtractTest2 is a test case for operator -
		/// </summary>
		[TestMethod()]
		public void SubtractOpVectorVectorTest()
		{
			Sharp3D.Math.Core.Vector2D left = new Vector2D(10, 10);
			Sharp3D.Math.Core.Vector2D right = new Vector2D(9, 8);

			Sharp3D.Math.Core.Vector2D expected = new Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D actual;

			actual = left - right;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// MultiplyTest2 is a test case for operator *
		/// </summary>
		[TestMethod()]
		public void MultiplyOpVectorScalarTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(1, 2);
			double scalar = 2;

			Sharp3D.Math.Core.Vector2D expected = new Vector2D(2, 4);
			Sharp3D.Math.Core.Vector2D actual;

			actual = vector * scalar;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// MultiplyTest3 is a test case for operator *
		/// </summary>
		[TestMethod()]
		public void MultiplyOpScalarVectorTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(1, 2);
			double scalar = 2;

			Sharp3D.Math.Core.Vector2D expected = new Vector2D(2, 4);
			Sharp3D.Math.Core.Vector2D actual;

			actual = scalar * vector;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// DivideTest6 is a test case for operator /
		/// </summary>
		[TestMethod()]
		public void DivideScalarVectorTest()
		{
			double scalar = 24.0;
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(2, 3);

			Sharp3D.Math.Core.Vector2D expected = new Vector2D(12, 8);
			Sharp3D.Math.Core.Vector2D actual;

			actual = scalar / vector;
			Assert.AreEqual(expected, actual);
		}
		/// <summary>
		/// DivideTest7 is a test case for operator /
		/// </summary>
		[TestMethod()]
		public void DivideVectorScalarTest()
		{
			Sharp3D.Math.Core.Vector2D vector = new Vector2D(2, 4);
			double scalar = 2.0;

			Sharp3D.Math.Core.Vector2D expected = new Vector2D(1, 2);
			Sharp3D.Math.Core.Vector2D actual;

			actual = vector / scalar;
			Assert.AreEqual(expected, actual);
		}
		#endregion

		#region Index Operator Tests
		/// <summary>
		/// ItemTest is a test case for this[int index]
		/// </summary>
		[TestMethod()]
		public void ItemTest()
		{
			Sharp3D.Math.Core.Vector2D target = new Vector2D(1, 2);

			Assert.AreEqual(target.X, target[0]);
			Assert.AreEqual(target.Y, target[1]);
		}
		[TestMethod()]
		[ExpectedException(typeof(System.IndexOutOfRangeException))]
		public void ItemTest1()
		{
			Vector2D vector = new Vector2D(1, 2);
			vector[2]++;
		}
		#endregion
	}
}
